name: Build and Release OTA Extractor

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python (Windows/Linux)
      if: runner.os != 'macOS'
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Set up Python for x86_64 on macOS
      if: runner.os == 'macOS'
      run: |
        sudo softwareupdate --install-rosetta --agree-to-license
        arch -x86_64 /usr/local/bin/python3 -m pip install --no-cache-dir --upgrade pip setuptools wheel

    - name: Upgrade pip
      if: runner.os != 'macOS'
      run: python -m pip install --upgrade pip

    - name: Install Dependencies (Windows/Linux)
      if: runner.os != 'macOS'
      run: pip install --no-cache-dir -r requirements.txt pyinstaller

    - name: Install Dependencies (macOS x86_64)
      if: runner.os == 'macOS'
      run: |
        arch -x86_64 python3 -m pip install --no-cache-dir -r requirements.txt pyinstaller

    - name: Build Executable
      run: |
        pyinstaller --onefile --windowed --name "OTA_Extractor" main.py
      shell: bash

    - name: Upload to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
