name: Build and Release OTA Extractor

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, windows-latest]  # Используем macOS Intel!

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10.4"

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install Dependencies
      run: pip install --no-cache-dir -r requirements.txt pyinstaller

    - name: Build Executable
      run: |
        pyinstaller --onefile --windowed --name "OTA_Extractor" main.py
      shell: bash

    - name: Upload to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
